services:
  excessus-db:
    container_name: excessus-db
    image: postgres:14.1-alpine
    restart: always

    environment:
      - POSTGRES_USER=excessus
      - POSTGRES_PASSWORD=excessus
    ports:
      - "4242:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
